"""Schema-backed configuration for ImageProcessor (LLD §3).

`models` turns a configuration document into frozen values; `validate` is the pre-commit
candidate validator the component registers with the core. Import both from here.
"""

from image_processor.config.models import (
    MAX_INLINE_BYTES,
    MUTATING_ACTIONS,
    CameraBinding,
    CollisionPolicy,
    CompletionPolicy,
    ComponentConfig,
    ConfigError,
    DecisionSignal,
    GpuConfig,
    ModelActivation,
    ModelEntry,
    ModelSourcesConfig,
    OutputsConfig,
    Paths,
    PublishConfig,
    ReadinessConfig,
    ReadinessMode,
    RouteConfig,
    RuntimeConfig,
    SchedulerConfig,
    SigningConfig,
    SpoolSourceConfig,
    TriggerSourceConfig,
    TrustedKey,
    parse_component_config,
)
from image_processor.config.validate import (
    CONFIG_SCHEMA,
    INFERENCE_RESULT_SCHEMA,
    MODEL_BUNDLE_MANIFEST_SCHEMA,
    VALIDATOR_NAME,
    load_schema,
    register,
    schema_path,
    validate_candidate,
)

__all__ = [
    "CONFIG_SCHEMA",
    "INFERENCE_RESULT_SCHEMA",
    "MAX_INLINE_BYTES",
    "MODEL_BUNDLE_MANIFEST_SCHEMA",
    "MUTATING_ACTIONS",
    "VALIDATOR_NAME",
    "CameraBinding",
    "CollisionPolicy",
    "CompletionPolicy",
    "ComponentConfig",
    "ConfigError",
    "DecisionSignal",
    "GpuConfig",
    "ModelActivation",
    "ModelEntry",
    "ModelSourcesConfig",
    "OutputsConfig",
    "Paths",
    "PublishConfig",
    "ReadinessConfig",
    "ReadinessMode",
    "RouteConfig",
    "RuntimeConfig",
    "SchedulerConfig",
    "SigningConfig",
    "SpoolSourceConfig",
    "TriggerSourceConfig",
    "TrustedKey",
    "load_schema",
    "parse_component_config",
    "register",
    "schema_path",
    "validate_candidate",
]
